# Generated by Django 5.0.6 on 2026-06-14 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('trial', 'Trial (30 days)'), ('basic', 'Basic — NPR 999/mo'), ('standard', 'Standard — NPR 2,499/mo'), ('premium', 'Premium — NPR 4,999/mo')], default='trial', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('stripe', 'Stripe / Card'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('trial_start', models.DateTimeField(auto_now_add=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('esewa_ref', models.CharField(blank=True, max_length=100)),
                ('khalti_ref', models.CharField(blank=True, max_length=100)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('max_listings', models.PositiveIntegerField(default=5, help_text='Max active listings for this plan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='users.agentprofile')),
            ],
        ),
    ]
