# Generated by Django 5.0.6 on 2026-05-23 14:40

import apps.properties.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('listing_type', models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent'), ('lease', 'For Lease')], max_length=10)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('land', 'Land'), ('luxury', 'Luxury / Hospitality')], max_length=20)),
                ('property_type', models.CharField(choices=[('flat', 'Flat / Apartment'), ('house', 'House'), ('bungalow', 'Bungalow'), ('penthouse', 'Penthouse'), ('villa', 'Villa'), ('hotel', 'Hotel'), ('resort', 'Resort'), ('shop', 'Shop'), ('office', 'Office'), ('plot', 'Plot')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('rented', 'Rented'), ('inactive', 'Inactive')], default='draft', max_length=20)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price', models.BigIntegerField(help_text='In NPR paisa')),
                ('price_negotiable', models.BooleanField(default=False)),
                ('area_sqm', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('living_rooms', models.PositiveSmallIntegerField(default=0)),
                ('kitchens', models.PositiveSmallIntegerField(default=0)),
                ('floors', models.PositiveSmallIntegerField(default=0)),
                ('built_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_luxury', models.BooleanField(db_index=True, default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('brochure_pdf', models.FileField(blank=True, null=True, upload_to='brochures/')),
                ('nearby_amenities', models.JSONField(blank=True, default=list)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.properties.models.media_upload_path)),
                ('thumbnail', models.ImageField(blank=True, help_text='Auto-generated for videos; uploaded alongside images optionally', null=True, upload_to=apps.properties.models.thumbnail_upload_path)),
                ('caption', models.CharField(blank=True, max_length=160)),
                ('media_type', models.CharField(choices=[('gallery', 'Gallery photo'), ('floorplan', 'Floor plan'), ('video_tour', 'Property tour video'), ('video_360', '360° video'), ('video_live', 'Live view clip'), ('panorama', '360° panorama photo')], max_length=20)),
                ('mime_type', models.CharField(blank=True, help_text='e.g. image/jpeg, video/mp4 — set on upload', max_length=80)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary gallery photo used as listing thumbnail')),
                ('processing_status', models.CharField(choices=[('pending', 'Processing'), ('ready', 'Ready'), ('failed', 'Processing failed')], default='ready', help_text='Set to PENDING when video needs transcoding, READY when playable', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SavedListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
