# Generated by Django 5.0.6 on 2026-05-23 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_rename_propertymedia_property_to_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='agent',
            field=models.ForeignKey(limit_choices_to={'is_agent': True}, on_delete=django.db.models.deletion.PROTECT, related_name='listed_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertymedia',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.property'),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='properties.property'),
        ),
        migrations.AddField(
            model_name='savedlisting',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_listings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['status', 'listing_type', 'category'], name='properties__status_4bb8cd_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['city', 'status'], name='properties__city_eb43d5_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_luxury', 'status'], name='properties__is_luxu_185909_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymedia',
            index=models.Index(fields=['listing', 'media_type'], name='properties__listing_065071_idx'),
        ),
        migrations.AddIndex(
            model_name='propertymedia',
            index=models.Index(fields=['listing', 'is_primary'], name='properties__listing_9ace1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'property')},
        ),
    ]
