# Generated by Django 5.0.6 on 2026-06-14 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_propertymedia_property_to_listing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedlisting',
            name='property',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='properties.property'),
        ),
        migrations.RenameField(
            model_name='savedlisting',
            old_name='property',
            new_name='listing',
        ),
        migrations.RenameIndex(
            model_name='propertymedia',
            new_name='properties__propert_82d238_idx',
            old_name='properties__listing_065071_idx',
        ),
        migrations.RenameIndex(
            model_name='propertymedia',
            new_name='properties__propert_ea7d50_idx',
            old_name='properties__listing_9ace1e_idx',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(blank=True, default=list, help_text='e.g. ["water_supply","electricity","internet"]'),
        ),
        migrations.AddField(
            model_name='property',
            name='bank_loan_eligible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='built_area_sqft',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Building/house area in sq ft', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='built_year_bs',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Bikram Sambat year', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='facing_direction',
            field=models.CharField(blank=True, choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('north_east', 'North-East'), ('north_west', 'North-West'), ('south_east', 'South-East'), ('south_west', 'South-West')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='furnishing_status',
            field=models.CharField(blank=True, choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-furnished')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='parking',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='road_access_ft',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Road access width in feet', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='road_type',
            field=models.CharField(blank=True, choices=[('main_road', 'Main Road'), ('side_road', 'Side Road'), ('highway', 'Highway'), ('private_street', 'Private Street'), ('alley', 'Alley / Galli')], max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='sewage_system',
            field=models.CharField(blank=True, help_text='e.g. Septic tank, Municipal sewer', max_length=40),
        ),
        migrations.AddField(
            model_name='property',
            name='water_source',
            field=models.CharField(blank=True, help_text='e.g. Municipal, Boring, Well', max_length=40),
        ),
        migrations.AlterField(
            model_name='propertymedia',
            name='listing',
            field=models.ForeignKey(db_column='property_id', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.property'),
        ),
        migrations.AlterUniqueTogether(
            name='savedlisting',
            unique_together={('user', 'listing')},
        ),
    ]
